### ISSUE TITLE
Should we check for existence of Class so we don't get an error of class not found?

### ISSUE THREAD

**Issue by banglashi** [arillo/silverstripe-utils#1]
Either that or we should trigger a warning message. What do you think @bumbus ?

https://github.com/arillo/silverstripe-utils/blob/53fa5952e8a2b7a9671dc7f9ab64c502ab9182c9/src/PageHelper.php#L44

**Comment by bumbus** [comment]
We could throw a `user_error` in case of non `live` mode, i guess, otherwise fall back to `Page` or `SiteTree`, what do you think?

**Comment by banglashi** [comment]
sounds great ;)
